# Copyright (C) 2011-2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/tianchi/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sony/tianchi/proprietary/bin/chargemon:system/bin/chargemon \
    vendor/sony/tianchi/proprietary/bin/illumination_service:system/bin/illumination_service \
    vendor/sony/tianchi/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
    vendor/sony/tianchi/proprietary/bin/updatemiscta:system/bin/updatemiscta \
    vendor/sony/tianchi/proprietary/etc/acdbdata/Liquid/Liquid_Handset_cal.acdb:system/etc/acdbdata/Liquid/Liquid_Handset_cal.acdb \
    vendor/sony/tianchi/proprietary/etc/acdbdata/Liquid/Liquid_Speaker_cal.acdb:system/etc/acdbdata/Liquid/Liquid_Speaker_cal.acdb \
    vendor/sony/tianchi/proprietary/etc/acdbdata/MTP/MTP_Handset_cal.acdb:system/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/sony/tianchi/proprietary/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:system/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/sony/tianchi/proprietary/etc/firmware/touch_chip_id_0x74_config_id_0x0011.bin:system/etc/firmware/touch_chip_id_0x74_config_id_0x0011.bin \
    vendor/sony/tianchi/proprietary/etc/firmware/touch_chip_id_0x74_config_id_0x0460.bin:system/etc/firmware/touch_chip_id_0x74_config_id_0x0460.bin \
    vendor/sony/tianchi/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0010.bin:system/etc/firmware/touch_chip_id_0x75_config_id_0x0010.bin \
    vendor/sony/tianchi/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0012.bin:system/etc/firmware/touch_chip_id_0x75_config_id_0x0012.bin \
    vendor/sony/tianchi/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0013.bin:system/etc/firmware/touch_chip_id_0x75_config_id_0x0013.bin \
    vendor/sony/tianchi/proprietary/etc/firmware/touch_module_id_0x43.img:system/etc/firmware/touch_module_id_0x43.img \
    vendor/sony/tianchi/proprietary/etc/firmware/touch_module_id_0x44.img:system/etc/firmware/touch_module_id_0x44.img \
    vendor/sony/tianchi/proprietary/etc/mixer_paths.xml:system/etc/mixer_paths.xml \
    vendor/sony/tianchi/proprietary/etc/sensor_def_qcomdev.conf:system/etc/sensor_def_qcomdev.conf \
    vendor/sony/tianchi/proprietary/etc/sensors_calib.conf:system/etc/sensors_calib.conf \
    vendor/sony/tianchi/proprietary/etc/sysmon.cfg:system/etc/sysmon.cfg \
    vendor/sony/tianchi/proprietary/lib/libcald_hal.so:system/lib/libcald_hal.so \
    vendor/sony/tianchi/proprietary/lib/libsysmon_jni.so:system/lib/libsysmon_jni.so \
    vendor/sony/tianchi/proprietary/usr/idc/clearpad.idc:system/usr/idc/clearpad.idc \
    vendor/sony/tianchi/proprietary/usr/idc/max1187x_pen_0.idc:system/usr/idc/max1187x_pen_0.idc \
    vendor/sony/tianchi/proprietary/usr/idc/max1187x_touchscreen_0.idc:system/usr/idc/max1187x_touchscreen_0.idc \
    vendor/sony/tianchi/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/sony/tianchi/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/sony/tianchi/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/sony/tianchi/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/sony/tianchi/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/sony/tianchi/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/sony/tianchi/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/sony/tianchi/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so
